config/routes.rb
Rails.application.routes.draw do
  root 'passengers/home#index'

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admins do
    root to: 'home#index'

    resources :flights
    resources :flight_classes, only: %i[edit update]

    resources :aeroplanes do
      resources :aeroplane_classes
    end
  end

  namespace :passengers do
    resource :flight_reservation, only: %i[edit update]
    resources :flight_reservations, only: %i[create]
  end
end

app/controllers/admins/home_controller.rb
module Admins
  class HomeController < ApplicationController
    def index
    end
  end
end

app/controllers/passengers/home_controller.rb
module Passengers
  class HomeController < ApplicationController
    before_action :init_upcoming_flights

    def index
      @flight_reservation = FlightReservation.new
    end
  end
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/passenger/home_helper.rb
module Passenger::HomeHelper
end

app/views/admins/home/index.html.erb
<div class="row">
  <div class="col text-center">
    <div class="card shadow rounded">
      <h4 class="card-header bg-primary bg-gradient text-white"><%= crud_t(Aeroplane, :index) %></h4>
      <div class="card-body">
        <p class="card-text"><%= t('.aeroplanes.body') %></p>
        <%= link_to t('here'), admins_aeroplanes_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <div class="col text-center">
      <div class="card shadow rounded">
      <h4 class="card-header bg-primary bg-gradient text-white"><%= crud_t(Flight, :index) %></h4>
      <div class="card-body">
        <p class="card-text"><%= t('.flights.body') %></p>
        <%= link_to t('here'), admins_flights_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>