config/routes.rb
Rails.application.routes.draw do
  root 'passengers/home#index'

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admins do
    root to: 'home#index'

    resources :flights
    resources :flight_classes, only: %i[edit update]

    resources :aeroplanes do
      resources :aeroplane_classes
    end
  end

  namespace :passengers do
    resource :flight_reservation, only: %i[edit update]
    resources :flight_reservations, only: %i[create]
  end
end

app/controllers/admins/home_controller.rb
module Admins
  class HomeController < ApplicationController
    def index
    end
  end
end

app/controllers/passengers/application_controller.rb
module Passengers
  class ApplicationController < ::ApplicationController
    protected

    def init_upcoming_flights
      @flights = Flight.upcoming.includes(flight_classes: :aeroplane_class)
    end
  end
end

app/controllers/passengers/flight_reservations_controller.rb
module Passengers
  class FlightReservationsController < ApplicationController
    before_action :set_flight_reservation, :set_flight_seats, only: %i[edit update]
    before_action :set_flight_seat, only: :update
    before_action :init_flight_reservation, :check_seats_availability, only: :create
    before_action :init_upcoming_flights, only: :create

    helper_method :resource_klass

    def edit; end

    def update
      if @flight_reservation.update(flight_seat: @flight_seat)
        redirect_to root_url,
                    notice: success_message(resource_klass, :update)
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def create
      if @flight_reservation.save
        redirect_to(
          root_url,
          notice: t(
            '.success',
            pnr: @flight_reservation.pnr,
            price: @flight_reservation.flight_class.seat_price
          )
        )
      else
        render 'passengers/home/index', status: :unprocessable_entity
      end
    end

    protected


    def resource_klass
      FlightReservation
    end

    def set_flight_seat
      @flight_seat = FlightSeat.find(params[:flight_seat_id])

      available_seat = @flight_seat.flight_class_id == @flight_reservation.flight_class_id
      available_seat ||= @flight_seat.flight.empty_seats?(@flight_seat.flight_class)
      return if available_seat

      redirect_to request.referrer, error: t('passengers.flight_classes.errors.no_seats')
    rescue ActiveRecord::RecordNotFound
      redirect_to request.referrer, error: t('passengers.flight_seats.errors.invalid')
    end

    def set_flight_seats
      @flight_seats = @flight_reservation.flight.flight_seats.includes(
        :flight_class
      ).order(:position, :row_number, :col_number)
    end

    def set_flight_reservation
      @flight_reservation = FlightReservation.find_by!(
        flight_id: params[:flight_id],
        pnr: params[:pnr]
      )
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, error: t('passengers.flight_reservations.errors.invalid')
    end

    def init_flight_reservation
      @flight_reservation = FlightReservation.new(flight_reservation_params)

      @flight_reservation.flight = Flight.upcoming.find(flight_id_param)
      @flight_reservation.flight_class =
        @flight_reservation.flight.flight_classes.find(
          flight_class_id_param
        )
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, error: t('passengers.flights.errors.invalid')
    end

    def flight_reservation_params
      params.require(:flight_reservation).permit(:user_name)
    end

    def flight_id_param
      params.require(:flight_reservation).fetch(:flight_id)
    end

    def flight_class_id_param
      params.require(:flight_reservation).fetch(:flight_class_id)
    end

    def check_seats_availability
      return if @flight_reservation.flight.empty_seats?(@flight_reservation.flight_class)

      redirect_to root_url, error: t('passengers.flight_classes.errors.no_seats')
    end
  end
end

app/controllers/passengers/home_controller.rb
module Passengers
  class HomeController < ApplicationController
    before_action :init_upcoming_flights

    def index
      @flight_reservation = FlightReservation.new
    end
  end
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/passenger/home_helper.rb
module Passenger::HomeHelper
end

app/views/passengers/home/index.html.erb
<div class="row">
  <div class="col shadow-sm p-3 mb-5 bg-body rounded">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag 'i_1.jpg', class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag 'i_2.jpg', class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag 'i_3.jpg', class: "d-block w-100" %>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden"><%= t('.previous') %></span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden"><%= t('.next') %></span>
      </button>
    </div>
  </div>
</div>

<%= render "shared/flash_messages" %>

<div class="row">
  <div class="col mb-5">
    <div class="card shadow rounded">
      <h4 class="card-header bg-primary bg-gradient text-white"><%= t('.upcoming') %></h4>
      <div class="card-body">
        <div class="accordion" id="accordionFlights">
          <% @flights.each_with_index do |flight, i| %>
            <div class="accordion-item">
              <h2 class="accordion-header" id="flight<%= flight.id %>">
                <button class="accordion-button collapsed" type="button" 
                        data-bs-toggle="collapse" data-bs-target="#collapse<%= flight.id %>"
                        aria-expanded="false" aria-controls="collapse<%= flight.id %>">
                  <%= flight.name %>
                </button>
              </h2>
              <div id="collapse<%= flight.id %>" class="accordion-collapse collapse"
                  aria-labelledby="flight<%= flight.id %>" data-bs-parent="#accordionFlights">
                <div class="accordion-body">

                  <table class="table">
                    <thead>
                      <tr>
                        <th><%= Flight.human_attribute_name(:code) %></th>
                        <th><%= Flight.human_attribute_name(:departure_date) %></th>
                        <th><%= t('.available_classes') %></th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th><%= flight.id %></th>
                        <td><%= flight.departure_date.strftime("%e %b %Y, %I:%M%p") %></td>
                        <td>
                            <% flight.flight_classes.each do |flight_class| %>
                              <div class="row">
                                <div class="col">
                                  <strong><%= flight_class.aeroplane_class.category %></strong>
                                </div>

                                <div class="col">
                                  <strong><%= t('.code') %>:</strong> <%= flight_class.id %>
                                </div>

                                <div class="col">
                                  <%= flight_class.seat_price %> <%= t('egp') %>
                                </div>
                              </div>
                            <% end %>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row align-items-center">
  <div class="col mb-5 me-5">
    <div class="card shadow rounded">
      <h4 class="card-header bg-primary bg-gradient text-white">
        <%= t('.create_reservation') %>
      </h4>
      <div class="card-body">
        <%= form_for([:passengers, @flight_reservation] ) do |form| %>
          <% if @flight_reservation.errors.any? %>
            <div class="text-danger">
              <p>
                <%=
                  validation_errors_t(
                    @flight_reservation.class, @flight_reservation.errors.count
                  )
                %>
              </p>
              <ul>
                <% @flight_reservation.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="mb-3">
            <%= form.label :user_name, class: "form-label" %>
            <%= form.text_field :user_name, class: "form-control" %>
          </div>

          <div class="mb-3">
            <%= form.label :flight_id, class: "form-label" %>
            <%= form.number_field :flight_id, class: "form-control" %>
          </div>

          <div class="mb-3">
            <%= form.label :flight_class_id, class: "form-label" %>
            <%= form.number_field :flight_class_id, class: "form-control" %>
          </div>

          <%= form.submit t('create'), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col mb-5">
    <div class="card shadow rounded">
      <h4 class="card-header bg-primary bg-gradient text-white">
        <%= t('.seat_location') %>
      </h4>
      <div class="card-body">
        <p><%= t('.seat_note') %></p>
        <%= form_with(url: edit_passengers_flight_reservation_path, method: :get) do |form| %>
          <div class="mb-3">
            <%=
              form.label :pnr, FlightReservation.human_attribute_name('pnr'),
                         class: "form-label"
            %>
            <%= form.text_field :pnr, class: "form-control" %>
          </div>

          <div class="mb-3">
            <%=
              form.label :flight_id, t('helpers.label.flight_reservation.flight_id'),
                          class: "form-label"
            %>
            <%= form.number_field :flight_id, class: "form-control" %>
          </div>

          <%= form.submit t('find'), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>