config/routes.rb
Rails.application.routes.draw do
  root 'passengers/home#index'

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admins do
    root to: 'home#index'

    resources :flights
    resources :flight_classes, only: %i[edit update]

    resources :aeroplanes do
      resources :aeroplane_classes
    end
  end

  namespace :passengers do
    resource :flight_reservation, only: %i[edit update]
    resources :flight_reservations, only: %i[create]
  end
end

app/views/layouts/admins/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('admins.header') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col text-center shadow-sm p-3 my-3 rounded text-white bg-primary bg-gradient">
          <h2><%= link_to t('admins.header'), admins_root_path, class: "text-decoration-none text-reset" %></h2>
        </div>
      </div>
      
      <% if admin_signed_in? %>
        <div class="row mb-4">
          <div class="col">
            <nav class="navbar navbar-expand-lg bg-light">
              <div class="container-fluid">
                <div class="collapse navbar-collapse">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <% selected_link = activated_nav_link %>
                    <li class="nav-item">
                      <%=
                        link_to(
                          t('admins.home.title'), admins_root_path,
                          class: "nav-link #{'active' if selected_link == :home}",
                          'aria-current': "page"
                        )
                      %>
                    </li>

                    <li class="nav-item">
                      <%=
                        link_to(
                          crud_t(Aeroplane, :index), admins_aeroplanes_path,
                          class: "nav-link #{'active' if selected_link == :aeroplanes}",
                          'aria-current': "page"
                        )
                      %>
                    </li>

                    <li class="nav-item">
                      <%=
                        link_to(
                          crud_t(Flight, :index), admins_flights_path,
                          class: "nav-link #{'active' if selected_link == :flights}",
                          'aria-current': "page"
                        )
                      %>
                    </li>

                    <li class="nav-item">
                      <%= 
                        link_to(
                          t('admins.log_out'), destroy_admin_session_path,
                          class: "nav-link ", data: { "turbo-method": :delete }
                        )
                      %>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>
        </div>
      <% end %>

      <%= render "shared/flash_messages" %>
      
      <div class="row mx-5">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>    
  </body>
</html>