config/routes.rb
Rails.application.routes.draw do
  root 'passengers/home#index'

  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  namespace :admins do
    root to: 'home#index'

    resources :flights
    resources :flight_classes, only: %i[edit update]

    resources :aeroplanes do
      resources :aeroplane_classes
    end
  end

  namespace :passengers do
    resource :flight_reservation, only: %i[edit update]
    resources :flight_reservations, only: %i[create]
  end
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :aeroplane

  has_many :flight_classes, dependent: :destroy
  has_many :flight_seats, dependent: :destroy

  has_many :flight_reservations, dependent: :restrict_with_error

  after_commit :prepare_seats_prices, if: :saved_change_to_aeroplane_id?

  validates :name, :departure_date, presence: true
  validate :furture_departure_date, on: %i[update create]

  scope :upcoming, -> { where("departure_date > ?", Time.now) }

  def reservations?
    !seats_ready || flight_reservations.exists?
  end

  def empty_seats?(flight_class)
    flight_reservations.where(
      flight_id: id, flight_class_id: flight_class.id
    ).count < flight_class.aeroplane_class.total_seats
  end

  private

  def furture_departure_date
    return if departure_date&.future?

    errors.add(:departure_date, :past)
  end

  def prepare_seats_prices
    update_columns(seats_ready: false)

    # CreateSeatsClassesWorker.perform_async(id)
    CreateSeatsClassesWorker.new.perform(id)
  end
end

app/controllers/admins/flights_controller.rb
module Admins
  class FlightsController < ApplicationController
    before_action :set_flight, only: %i[ show edit update destroy ]
    before_action :check_changing_ability, only: %i[edit update destroy]

    helper_method :resource_klass

    # GET /flights or /flights.json
    def index
      @flights = Flight.all
    end
  
    # GET /flights/1 or /flights/1.json
    def show
      @flight_classes = @flight.flight_classes.includes(:aeroplane_class).order_position
      @has_reservations = @flight.reservations?
    end
  
    # GET /flights/new
    def new
      @flight = Flight.new
    end
  
    # GET /flights/1/edit
    def edit
    end
  
    # POST /flights or /flights.json
    def create
      @flight = Flight.new(flight_params)
  
        if @flight.save
          redirect_to admins_flight_url(@flight),
                      notice: success_message(resource_klass, :create)
        else
          render :new, status: :unprocessable_entity
        end
    end
  
    # PATCH/PUT /flights/1 or /flights/1.json
    def update
      if @flight.update(flight_params)
        redirect_to admins_flight_url(@flight),
                    notice: success_message(resource_klass, :update)
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    # DELETE /flights/1 or /flights/1.json
    def destroy
      @flight.destroy
  
      redirect_to admins_flights_url,
                  notice: success_message(resource_klass, :destroy)
    end
  
    private

    def resource_klass
      Flight
    end

    def check_changing_ability
      return true unless @flight.reservations?

      redirect_to admins_flight_url(@flight), error: t('admins.flights.errors.reservations_exists')
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
      @breadcrumbs[:flight] = { id: @flight.id, name: @flight.name }
    end

    # Only allow a list of trusted parameters through.
    def flight_params
      params.require(:flight).permit(:name, :aeroplane_id, :departure_date)
    end
  end  
end

app/helpers/flights_helper.rb
module FlightsHelper
  def money_diff(flight_reservation, flight_class)
    current_price = flight_reservation.flight_class.seat_price
    current_class_price = flight_class.seat_price

    current_class_price - current_price
  end

  def current_seat?(seat, reservation)
    seat.id == reservation.flight_seat_id
  end

  def seats_status(flight)
    flight.seats_ready ? t('yes') : t('no')
  end

  def disabled_seat?(seat, reservation)
    !(
      seat.id == reservation.flight_seat_id ||
        (
          reservation.flight_seat_id_changed? &&
          seat.id == reservation.flight_seat_id_was
        )
    ) && !seat.availability
  end
end

app/views/admins/flights/_form.html.erb
<%= form_for([:admins, flight]) do |form| %>
  <% if flight.errors.any? %>
    <div class="text-danger">
      <p>
        <%= validation_errors_t(resource_klass, flight.errors.count) %>
      </p>
      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :aeroplane_id, class: 'form-label' %>
    <%= form.number_field :aeroplane_id, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :departure_date, class: 'form-label' %>
    <%= form.datetime_field :departure_date, class: 'form-control' %>
  </div>

  <%= form.submit t('save'), class: "btn btn-primary" %>
<% end %>

app/views/admins/flights/edit.html.erb
<%= render "shared/breadcrumbs", current_page: :edit_admins_flight  %>

<div class="card shadow rounded">
  <h4 class="card-header bg-primary bg-gradient text-white">
    <%= crud_t(resource_klass, :edit) %>
  </h4>
  <div class="card-body">
    <%= render "form", flight: @flight %>
  </div>
</div>

app/views/admins/flights/index.html.erb
<%= render "shared/breadcrumbs", current_page: :admins_flights  %>

<div class="row">
  <div class="col"><h3><%= crud_t(resource_klass, :index) %></h3></div>
  <div class="col-auto">
    <%= link_to crud_t(resource_klass, :new), new_admins_flight_path, class: "btn btn-primary" %>
  </div>
</div>

<table class="table table-hover mt-2">
  <thead>
    <tr>
      <% %i[id name seats_ready departure_date].each do |attr_name|  %>
        <th scope="col"><%= resource_klass.human_attribute_name(attr_name) %></th>
      <% end %>
      <th scope="col"><%= Aeroplane.human_attribute_name(:name) %></th>
      <th scope="col"> - </th>
    </tr>
  </thead>
  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <th scope="row"><%= flight.id %></th>
        <td><%= flight.name %></td>
        <td><%= seats_status(flight) %></td>
        <td><%= flight.departure_date %></td>
        <td><%= flight.aeroplane.name %></td>
        <td><%= link_to t('show'), [:admins, flight] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/flights/new.html.erb
<%= render "shared/breadcrumbs", current_page: :new_admins_flight  %>

<div class="card shadow rounded">
  <h4 class="card-header bg-primary bg-gradient text-white">
    <%= crud_t(resource_klass, :new) %>
  </h4>
  <div class="card-body">
    <%= render "form", flight: @flight %>
  </div>
</div>

app/views/admins/flights/show.html.erb
<%= render "shared/breadcrumbs", current_page: :admins_flight  %>
<%= render "shared/destroy_confirmation"  %>

<div class="row mt-5">
  <div class="col"><h3><%= crud_t(resource_klass, :show) %></h3></div>
  <div class="col-auto">
    <% unless @has_reservations %>
      <%=
        link_to(
          t('edit'), edit_admins_flight_path(@flight), class: 'btn btn-primary', role: "button"
        )
      %>
      <%=
        link_to(
          t('destroy'), [:admins, @flight], class: 'btn btn-danger', role: "button", 
          data: {
            'turbo-confirm': destroy_confirmation_t(resource_klass, @flight.name),
            'turbo-method': 'delete'
          }
        )
      %>
    <% end %>
  </div>
</div>

<table id="flight" class="table table-hover mt-2">
  <thead>
    <tr>
      <% %i[id name seats_ready departure_date].each do |attr_name|  %>
        <th scope="col"><%= resource_klass.human_attribute_name(attr_name) %></th>
      <% end %>
      <th scope="col"><%= Aeroplane.human_attribute_name(:name) %></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= @flight.id %></th>
      <td><%= @flight.name %></td>
      <td><%= seats_status(@flight) %></td>
      <td><%= @flight.departure_date %></td>
      <td><%= @flight.aeroplane.name %></td>
    </tr>
  </tbody>
</table>


<% flight_class_klass = @flight_classes.klass %>
<h4 class="mt-5"><%= crud_t(flight_class_klass, :index) %></h4>

<% if @flight.seats_ready? %>
  <table id="flight_classes" class="table table-hover">
    <thead>
      <tr>
        <th scope="col"><%= flight_class_klass.human_attribute_name(:id) %></th>
        <th scope="col"><%= flight_class_klass.human_attribute_name(:seat_price) %></th>
        <% %i[category rows_number seats_per_row].each do |attr_name| %>
          <th scope="col"><%= AeroplaneClass.human_attribute_name(attr_name) %></th>
        <% end %>
        <% unless @has_reservations %>
          <th scope="col">-</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @flight_classes.each do |flight_class| %>
        <tr id="<%= dom_id flight_class %>">
          <th scope="row"><%= flight_class.id %></th>
          <td><%= flight_class.seat_price %></td>
          <td><%= flight_class.aeroplane_class.category %></td>
          <td><%= flight_class.aeroplane_class.rows_number %></td>
          <td><%= flight_class.aeroplane_class.seats_per_row %></td>
          <% unless @has_reservations %>
            <td>
              <%=
                link_to(
                  t('edit'), edit_admins_flight_class_path(flight_class),
                  class: 'btn btn-primary'
                )              
              %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>